# Any settings placed in this file will apply to all applications that 
# get thier config from the config server. Applications are able to 
# override any settings specified here so this file is a great place to 
# change any defaults for all the apps that are bootstraping from the 
# config server. 

# Expose the health endpoint details and make all actuator 
# end points visible without a password this is NOT recommend in 
# production but is useful for demos
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
